AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys an EKS cluster into VPC
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  EKSClusterName:
    Description: EKS Cluster Name
    Type: String
    Default: "EKS_Cluster"
  KubernetesVersion:
    Description: Kubernetes version used
    Type: String
    Default: "1.14"

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allows EKS to manage clusters on your behalf.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - eks.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  EKSControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group to allow EKS Cluster to communicate with worker nodes
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref EKSClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSControlPlaneSecurityGroup
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB1-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB2-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB3-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PRIV1-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PRIV2-SN"
          - Fn::ImportValue:
             !Sub "${EnvironmentName}-PRIV3-SN"
Outputs:
  EKSClusterName:
    Value: !Ref EKSCluster
    Description: EKS Cluster Name
    Export:
      Name: !Sub "${EnvironmentName}-EKS-Cluster"
  EKSClusterArn:
    Value: !GetAtt EKSCluster.Arn
    Description: EKS Cluster Arn
    Export:
      Name: !Sub "${EnvironmentName}-EKS-ClusterArn"
  EKSClusterEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
    Description: EKS Cluster Endpoint
    Export:
      Name: !Sub "${EnvironmentName}-EKS-ClusterEndpoint"
  EKSControlPlaneSecurityGroup:
    Value: !Ref EKSControlPlaneSecurityGroup
    Description: EKS ControlPlaneSecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-EKSControlPlaneSecurityGroup"